---
extends: default

ignore: |
  .venv/
  tests/
  examples/
  testing/
  smithery.yaml
  .github/ISSUE_TEMPLATE/

rules:
  line-length:
    max: 120
    level: warning
  trailing-spaces: disable
  indentation:
    spaces: 2
    indent-sequences: false
  document-start: disable
